export const ActionTypes={
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_PRODUCT:"REMOVE_PRODUCT",
    SET_FILTER:"SET_FILTER",
    SELECTED_FILTER:"SELECTED_FILTER",
    CLEAR_FILTER:"CLEAR_FILTER",
    ADD_PRODUCT:"ADD_PRODUCT",
    SET_QUANTITY:"SET_QUANTITY",
}